# John Locke (1632 - 1704)

Naturrecht als Grenze des Staates:
    1. Der Mensch im Naturzustand (S. 278)
	-Naturzustand = Naturrechte:
	Rechte auf Freiheit, Eigentum, Leben.
	Zustand der Gleicheit und der Vernuft.

    2. asdf

Gott hat uns das Leben geschenkt. Daher haben wir das Leben von keiner anderen Person, wir gehören keinem ausser Gott.
Selbsterhaltung ist eine Pflicht

Im Naturzustand gibt es kein allgemeines Recht, keine Gleichheit. Jeder entscheidet selber welche Strafen er verteilen will,
jeder ist sein eigener Richter.

Bildung einer politischen Gesellschaft nach John Locke:

|	Mängel im Naturzustand:		|	Verzicht von Rechten im Naturzustand:	|	Staatliche Gewalten:	|
|---------------------------------------|-----------------------------------------------|-------------------------------|
|Kein allgemeines Gesetz, keine		|Verzicht auf das Recht frei zu Sprechen	|	Judikative		|
|Sicherheit				|						|				|
|---------------------------------------|-----------------------------------------------|-------------------------------|
|					|						|	Exekutive		|
|					|						|				|
|					|						|				|
|---------------------------------------|-----------------------------------------------|-------------------------------|
|					|						|				|
|					|						|				|
|					|						|				|
|---------------------------------------|-----------------------------------------------|-------------------------------|
|					|						|				|
|					|						|				|
|					|						|				|
|---------------------------------------|-----------------------------------------------|-------------------------------|


## Lockes Staatsmodell:

> Wie in Hobbes Staatsmodell gibt das Volk ihre Macht dem Staat, aber im Gegensatz zu Hobbes Modell ist der Staat aufgeteilt,
> es gibt keine einzige Instanz die alle Macht hat. Die Macht ist in drei teile geteilt: Legislative, Judikative, Exekutive.
> Die Exekutive und die Judikative muss immer die von der Legislative festgelegten Regeln folgen.
